name: Heroku Continuous Deployment

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
    - name: Build and push
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/cise-week2.git
    - name: Release
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: git push --force heroku `git subtree split --prefix server HEAD`:master